# Generated by Django 4.0.6 on 2022-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksItem',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_price', models.FloatField()),
            ],
        ),
    ]
