# Generated by Django 4.0.6 on 2022-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksCart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_price', models.FloatField()),
                ('stock_unit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stocksitem',
            name='stock_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
