# Generated by Django 4.0.6 on 2022-07-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_api', '0002_stockscart_alter_stocksitem_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockscart',
            old_name='stock_unit',
            new_name='stock_quantity',
        ),
    ]
