# Generated by Django 4.0.6 on 2022-07-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_api', '0005_purchaseorder_delete_stockscart'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchase_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
