# Generated by Django 4.0.6 on 2022-07-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_api', '0006_userportfolio_purchaseorder_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='purchase_id',
            field=models.IntegerField(null=True),
        ),
    ]
